### ISSUE TITLE
crash with Object.keys(String.prototype)

### ISSUE THREAD

**Issue by targos** [devsnek/engine262#37]
```
> Object.keys(String.prototype)
TypeError: Assert failed
    at Evaluate_CallExpression$$1 (C:\Users\Michael\Documents\git\targos\engine262\dist\engine262.js:4233:18)
    at EvaluateCall$$1.next (<anonymous>)
    at EvaluateCall$$1 (C:\Users\Michael\Documents\git\targos\engine262\dist\engine262.js:4176:19)
    at Call$$1 (C:\Users\Michael\Documents\git\targos\engine262\dist\engine262.js:12810:13)
    at BuiltinFunctionValue.Call (C:\Users\Michael\Documents\git\targos\engine262\dist\engine262.js:19599:21)
    at nativeCall (C:\Users\Michael\Documents\git\targos\engine262\dist\engine262.js:19553:13)
    at BuiltinFunctionValue.Object_keys [as nativeFunction] (C:\Users\Michael\Documents\git\targos\engine262\dist\engine262.js:22304:19)
    at EnumerableOwnPropertyNames$$1 (C:\Users\Michael\Documents\git\targos\engine262\dist\engine262.js:13071:20)
    at StringExoticObjectValue.OwnPropertyKeys (C:\Users\Michael\Documents\git\targos\engine262\dist\engine262.js:19685:8)
    at Assert (C:\Users\Michael\Documents\git\targos\engine262\dist\engine262.js:35:12)
```

**Comment by targos** [comment]
It seems to be a problem with the code generated for `X(...)`.

This:
```js
    for (const P of O.properties.keys()) {
      if (isArrayIndex(P) && X(ToInteger(P)).numberValue() >= len) {
        keys.push(P);
      }
    }
```

Is transformed to:
```js
      for (const P of O.properties.keys()) {
        let _val4 = ToInteger$$1(P);

        Assert(!(_val4 instanceof AbruptCompletion), "");

        if (_val4 instanceof Completion) {
          _val4 = _val4.Value;
        }

        if (isArrayIndex$$1(P) && _val4.numberValue() >= len) {
          keys.push(P);
        }
      }
```

**Comment by devsnek** [comment]
#24
