### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by TimothyGu** [devsnek/engine262#73]
```
$ npx rollup -c

./src/api.mjs → dist/engine262.js, dist/engine262.mjs...
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src/intrinsics/RegExpPrototype.mjs (163:14)
161: 
162:   const first = S.stringValue().charCodeAt(index);
163:   if (first < 0xD800 || first > 0xDBFF) {
                   ^
164:     return new Value(index + 1);
165:   }
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/home/timothy-gu/dev/engine262/node_modules/rollup/dist/rollup.js:3597:30)
    at Module.error (/home/timothy-gu/dev/engine262/node_modules/rollup/dist/rollup.js:14376:9)
    at tryParse (/home/timothy-gu/dev/engine262/node_modules/rollup/dist/rollup.js:14039:16)
    at Module.setSource (/home/timothy-gu/dev/engine262/node_modules/rollup/dist/rollup.js:14095:35)
    at /home/timothy-gu/dev/engine262/node_modules/rollup/dist/rollup.js:17409:20
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:40:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:11)
    at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
```

**Comment by targos** [comment]
I already saw that. `rm -rf node_modules && npm i` fixed it

**Comment by TimothyGu** [comment]
Okie, that works here too. A patch to update deps is coming.

**Comment by TimothyGu** [comment]
See 1e216d9b0ade26b0adfe66e1ae89fd4afa10c233.
